### ISSUE TITLE
server repo template

### ISSUE THREAD

**Issue by aleksander-git** [aleksander-git/data-analyzer#5]
Подготовить шаблонные варианты репозитория для веб-сервера на го.
Выбрать один (или несколько) и обосновать. Можно вынести на обсуждение

**Comment by dadilll** [comment]
требуется дороботка логгера.

**Comment by kvizyx** [comment]
Хочу предложить использовать slog в качестве логгера и к нему хендлер с зерологом сделать. Типо такого - https://github.com/samber/slog-zerolog. Потом, если понадобится, можно будет любой другой логгер поставить.

Для него также есть готовый middleware - https://github.com/samber/slog-gin

**Comment by Aspandiyar933** [comment]
вау крутая идея


ср, 22 мая 2024 г. в 20:16, Kirill ***@***.***>:

**Comment by dadilll** [comment]
Да неплохая идея. Стоит ей занятся

**Comment by semyadmin** [comment]
> Хочу предложить использовать slog в качестве логгера и к нему хендлер с зерологом сделать. Типо такого - https://github.com/samber/slog-zerolog. Потом, если понадобится, можно будет любой другой логгер поставить.
> 
> Для него также есть готовый middleware - https://github.com/samber/slog-gin

Непонятно - а для чего? Использовать slog и еще обернуть его zero logs - это что бы красивый текст был в консоле? Может проще (ну не особо проще конечно) slog настроить? Он гибко настривается. На мой взгляд тяжеловато получается. 
А вообще нужно настроить логгер интерфейс и его во всех нужных местах принимать, а кто его будет реализовывать - это уже менее важно

**Comment by kvizyx** [comment]
То что я предложил, это просто адаптер хендлера слога к зерологу, в нём нет вообще ничего сложного. Можно конечно и самостоятельно настроить, но как по мне лучше уже готовое взять. Про интерфейс это да)

**Comment by dadilll** [comment]
ссылка на ветку https://github.com/aleksander-git/data-analyzer/tree/5-server-repo-template
