### ISSUE TITLE
Схема БД

### ISSUE THREAD

**Issue by aleksander-git** [aleksander-git/data-analyzer#6]
Подготовить схему БД для хранения следующих сущностей:

-  users
- datasets

Схему подготовить с помощью расширения https://marketplace.visualstudio.com/items?itemName=dineug.vuerd-vscode и положить в проект в docs/erd (подготовить MR)
В той же папке держать схему формате .sql (генерируется с помощью vuerd).  Т.е. в итоге там будет два файла - json и sql.

Подготовить файл миграции для инициализации БД (с помощью либы goose) и положить в  internal/database/backend/migrations - протестировать локально (развернуть у себя БД и применить миграцию + rollback)

**Comment by kvizyx** [comment]
Может лучше папку с миграциями в корень вынести? Что то типа db/migrations

**Comment by aleksander-git** [comment]
это внутрянка, ни вижу смысла смысла светить наружу

**Comment by kvizyx** [comment]
А мы решили уже какую бд будем использовать? Postgres/mysql или другое что то?

**Comment by kvizyx** [comment]
И ещё, мы будем сами авторизацию делать или через других провайдеров? Или и то, и другое?

**Comment by aleksander-git** [comment]
По БД - тебе какая ближе? Я думаю в нашем случае не принципиально. По авторизации - предлагай варианты, подумаем, обсудим

**Comment by kvizyx** [comment]
Я больше работал с постгресом, так что давайте его возьмём, тем более, что не принциписально) Насчёт авторизации - можно самим написать, можно какую-нибудь готовую штуку взять (auth0 например, давно хотел его попробовать). Но самим написать будет полезнее с точки зрения опыта. Что лучше?)

**Comment by aleksander-git** [comment]
Я никогда с autho0 не сталкивался, какой там принцип вкратце?
